services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Tests\Service\ApiServiceMock:
        decorates: 'http.client'
        decoration_inner_name: 'App\Tests\Service\ApiServiceMock.http.client'
        arguments: [ '@.inner' ]